### ISSUE TITLE
ESR (#4) - authentication

### ISSUE THREAD

**Issue by hubertdcruze** [commoncriteria/sdn-controller#14]
The SDN Controller shall provide an authentication mechanism for local and remote administrators, as well as the device/VM itself (e.g., the device/VM maintains an authentication credential that can be used to authenticate it to an administrator’s client).

**Comment by hubertdcruze** [comment]
Comments from TC meeting on Feb 8
Define local admin because it is optional in the NDcPP

**Comment by destineeb** [comment]
was the comment suggesting the requirement conflicts with the NDcPP? The SDN controller may extend certain reqs but it shouldn't conflict. 

_FIA_UAU_EXT.2.1 The TSF shall provide a local [selection: password-based, SSH public 
key-based, certificate-based, [assignment: other authentication mechanism(s)]] authentication 
mechanism to perform local administrative user authentication.__

**Comment by hubertdcruze** [comment]
May be suggesting that within the context of the NDcPP the definition or implementation of a local administrator role is not mandatory but optional. This could imply that the NDcPP allows for flexibility regarding whether or not a device should have a designated local administrator role defined within its security policy or configuration. The local administrator typically has elevated privileges for managing the device's settings and security directly on the device, as opposed to through network-based administration. Given this optionality, the statement underscores the need to explicitly decide and define the role and privileges of a local admin within the specific implementation or policy adhering to the NDcPP standards, if chosen to be included. 
And also as you mentioned, the SDN controller may extend certain reqs but it shouldn't conflict, I think in that way too.

**Comment by pbelani** [comment]
I think this is a reasonable approach and will fold into the conversation we have regarding PP vs. PP module (that inherits the controls from the base PP)
