### ISSUE TITLE
ESR (#12) - API

### ISSUE THREAD

**Issue by hubertdcruze** [commoncriteria/sdn-controller#18]
The SDN Controllers must adhere to relevant security standards and best practices for API security including REST security principles as recommended by OWASP, NIST, and ISO/IEC.

**Comment by hubertdcruze** [comment]
Comments from TC meeting on Feb 8
must be refined and more detailed, which specific SFRs and best practices should be clarified
be more specific – keep it for now...

**Comment by hubertdcruze** [comment]
A bit refined and more detailed, shared below, as suggested. Please let us know what you think, otherwise, we will keep the above ones. Please add/delete as you find appropriate:

1. SDN Controllers must comply with established security standards and implement best practices for API security, particularly emphasizing REST security principles. They are expected to follow guidelines set forth by recognized entities like OWASP, NIST, and ISO/IEC. This involves ensuring secure authentication, authorization, encryption, and coding practices, alongside conducting regular security evaluations and managing vulnerabilities to protect against current and emerging cyber threats.

2. SDN Controllers are mandated to conform to essential security standards, focusing on API security and REST security principles as outlined by leading organizations such as OWASP, NIST, and ISO/IEC. This includes adopting secure authentication and authorization practices, data encryption, and following secure coding guidelines. Additionally, they must engage in continual security assessments and vulnerability management to mitigate against a spectrum of cyber risks.

**Comment by erahn** [comment]
I'm concerned by calling out of REST in particular. If I have a product which uses gRPC, it sounds like I am excluded. I doubt this is the intent.

Would it be better to remove the line "particularly emphasizing REST security principles" from (1)?
