### ISSUE TITLE
ESR (#13) - services |  features/protocols 

### ISSUE THREAD

**Issue by hubertdcruze** [commoncriteria/sdn-controller#19]
By default, the SDN controller must turn-off any services or features/protocols that are not essential for its operation.

**Comment by hubertdcruze** [comment]
Comments from TC meeting Feb 8
#13 make it a positive. "The SDN controller must only have on….essential for its operation."
o Specify what we expect the minimum functions are and then allow for assignment of others that are essential
o Pull in SFRs that align with these requirements
o By default, the TSF shall enable only those services which are essential for functioning as a Software Defined Networking Controller. These shall include Northbound interfaces, southbound interfaces, remote administrative services [selection: ssh, https], and [assignment: other services as specified in the security target]

**Comment by hubertdcruze** [comment]
*** Please find below a few other ways to make it more positive. Please let us know which you find more reasonable ***

1. By default, the SDN controllers shall enable only those services which are essential for functioning as a Software Defined Networking Controller. These shall include Northbound interfaces, southbound interfaces, remote administrative services [selection: ssh & https], and [assigned: other services as specified in the security target]

2. The SDN controller, by default, smartly activates only those services, features, and protocols crucial for its optimal operation, ensuring efficiency and streamlined performance. Included in this scope are Northbound interfaces, Southbound interfaces, remote administrative services with SSH and HTTPS, and other services as outlined in the security target.

3.  Optimizing for peak performance, the SDN controller by default focuses on activating critical services, features, and protocols, ensuring a seamless and effective operational experience. This encompasses Northbound interfaces, Southbound interfaces, remote administrative services with SSH and HTTPS, along with additional services specified within the security target.

4. By design, the SDN controller prioritizes essential services, features, and protocols for activation, streamlining operations, and maximizing system effectiveness right from the start. The provisions cover Northbound interfaces, Southbound interfaces, remote administrative services with SSH and HTTPS, and any other services detailed in the security target.

5. Ensuring operational excellence, the SDN controller intuitively selects and activates only the indispensable services, features, and protocols, optimizing network performance and reliability. The scope includes Northbound and Southbound interfaces, along with remote administrative services (SSH, HTTPS), and further services as defined in the security target.

**Comment by destineeb** [comment]
Option 1
