### ISSUE TITLE
Assumptions

### ISSUE THREAD

**Issue by hubertdcruze** [commoncriteria/sdn-controller#22]
· Centralization of Control - A single SDN controller (or a centralized cluster acting as a single logical entity) can maintain a comprehensive view of the entire network and make decisions accordingly.

· Scalability - The SDN controller can scale to manage large networks spread over geographically dispersed locations.

· Real-Time Network State Information - The SDN controller has timely and accurate information about the network state to make informed decisions. Requires reliable and immediate data from network sensors and devices.

· Reliability and High Availability - The need for robust failover and redundancy strategies is critical so that the network remains operational even if individual components fail. The network devices (switches, routers) and the connections to the SDN controller must be reliable.

· Security - Network communications between the SDN controller and network devices are secure from unauthorized access and threats. Assuming secure environment for optimal controller performance.

· Compliance with Protocols and Standards - All components in the SDN architecture adhere to established protocols and standards to ensures that different network devices from various vendors can work together seamlessly. Any deviation by devices from these standards can disrupt network operations.

· Programmability - Network devices are programmable and can dynamically adjust their operations based on commands from the SDN controller to facilitate the implementation of sophisticated, dynamic network management strategies.

· Decoupling of Data and Control Planes - Effective separation of the data plane (traffic handling) and the control plane (traffic management) should be maintained to allow independent scaling and optimization of each plane. which requires careful implementation to prevent issues arising from the interdependencies.

· Underlying OS - The SDNC is hosted on an underlying operating system that is up to date with recommended security patches and is not compromised.

**Comment by destineeb** [comment]
Looks like we still need to add:

-  Real-Time Network State Information - The SDN controller has timely and accurate information about the network state to make informed decisions. Requires reliable and immediate data from network sensors and devices.
- · Underlying OS - The SDNC is hosted on an underlying operating system that is up to date with recommended security patches and is not compromised.
