### ISSUE TITLE
Add bullets to the Background and Purpose section of the SDNC ESR

### ISSUE THREAD

**Issue by njgengo** [commoncriteria/sdn-controller#25]
Hello to the GitHub Edit Team for the SDN Controller ESR:

Was wondering if you could help with the following changes to the SDN controller ESR?

1. Add the following additional definitions to the existing bullet list in the "Background and Purpose" section:
- The Data Plane and the Control Plan are decoupled so that data traffic remains in the Data Plane, and control traffic remains in the Control Plan.
- The SDN Controller has centralization of control so that all components of the SDN environment are under the control of the SDN Controller only.
- The SDN Controller can scale to manage large networks, typically spread over geographically dispersed locations.

**Comment by destineeb** [comment]
@zsmi can you help with the above?
