### ISSUE TITLE
ESR, Section Assumptions: merge physical assumptions

### ISSUE THREAD

**Issue by HolgerBlasumSYSGO** [commoncriteria/sdn-controller#4]
Section Assumptions 

# OLD
* Physical security appropriate to the value of the SDN Controller and the data it contains is provided.
*  An SDN Controller is protected from physical attacks by the wider environment."
# CHANGE TO (NEW)
* Physical security appropriate to the value of the SDN Controller and the data it contains is provided.  An SDN Controller is protected from physical attacks by the wider environment."
# Rationale
I think this is the same topic.

**Comment by HolgerBlasumSYSGO** [comment]
That is make, it one bullet point instead of two.

**Comment by njgengo** [comment]
Thanks for that insight. Will request the Edit Team to apply your suggested changed below:

Edit Team, please make the change, verbatim, as provided in the issue above (creditted to HolgerBlasumSYSGO). Thanks,

**Comment by jfisherbah** [comment]
change made 11/29, will be reflected in latest build
