### ISSUE TITLE
ESR, Section Attacker Access

### ISSUE THREAD

**Issue by HolgerBlasumSYSGO** [commoncriteria/sdn-controller#5]
ESR, Section Attacker Access 

# FROM (OLD)
"An attacker can take over the role of the SDN controller and thus compromise the entire network."
# CHANGE TO (NEW)
"An attacker can impersonate the role of the SDN controller in the network."
# Rationale
I think this is meant here. Otherwise, if the attacker would already have taken over the particular SDN controller this ESR wants to protect, it's game over anyway.

**Comment by HolgerBlasumSYSGO** [comment]
Oops, forget to write "can". Of course: "An attacker can impersonate the role of another SDN controller in the network."

**Comment by njgengo** [comment]
Thank you for suggesting the clarification, and providing the second suggestion. Below, I'll ask the Edit Team to make the change:

Edit Team, please make the following changes in the ESR (these are direct quotes from HolgerBlasumSYSGO, creditting their input):

FROM (OLD):
"An attacker can take over the role of the SDN controller and thus compromise the entire network."

CHANGE TO (NEW)
"An attacker can impersonate the role of the SDN controller in the network. An attacker can impersonate the role of another SDN controller in the network."

**Comment by pbelani** [comment]
@kgal @zsmi, @jmcdaniels  - Justin Fisher <Justin.Fisher@leidos.com> is part of our contractor edit team and is looking to make edits to the ESR based on these comments. Can you provide an assist to him and the necessary permissions for him to do this please?

**Comment by jfisherbah** [comment]
change made 11/29, will be reflected in latest build
