### ISSUE TITLE
ESR, Use Cases

### ISSUE THREAD

**Issue by tbrooks06** [commoncriteria/sdn-controller#6]
Add use case:  A SDN Controller for hyper-converge consisting of an amalgam of computing resources in a single unit for storage centric, server centric or even hybrid (storage-server) workloads. 

Rationale: Hyperconverged storage is  a software-defined approach which includes a software layer that virtualizes the resources in the node and shares them across all the nodes in a cluster, creating one large storage pool; SDN and load balancing determine which hardware to serve requests from.

**Comment by tbrooks06** [comment]
Add the above reference use case to the ESR.

**Comment by njgengo** [comment]
Thank you for your input. Will ask the Edit Team to make the change:

Edit Team, please make the change that was written in the issue above (creditted to tbrooks06). Thanks.

**Comment by jfisherbah** [comment]
change made 11/29, will be reflected in latest build. Only editorial change was to change "A SDN" to "An SDN" for consistency with other usage.
